# Server Port (Local par 8080 chalega, Cloud/Render par dynamic port uthayega)
server.port=${PORT:8080}

# JWT Token Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# Neon PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-small-pond-b56vcfz3-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gstHkqU8nQ9e
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Auto DDL Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Photo Base64 & File Upload Limits (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB